AWSTemplateFormatVersion: '2010-09-09'

Parameters:
  ClusterBaseName:
    Type: String
    Default: rey-eks-work
    Description: "EKS 클러스터의 기본 이름"

  TargetRegion:
    Type: String
    Default: ap-northeast-2
    Description: "AWS 리소스가 배포될 리전"

  AvailabilityZone1:
    Type: String
    Default: ap-northeast-2a
    Description: "첫 번째 가용 영역"

  AvailabilityZone2:
    Type: String
    Default: ap-northeast-2c
    Description: "두 번째 가용 영역"

  VpcBlock:
    Type: String
    Default: 10.100.0.0/16
    Description: "VPC의 IP 주소 범위"

  PublicSubnet1Block:
    Type: String
    Default: 10.100.1.0/24
    Description: "첫 번째 퍼블릭 서브넷의 IP 주소 범위"

  PublicSubnet2Block:
    Type: String
    Default: 10.100.2.0/24
    Description: "두 번째 퍼블릭 서브넷의 IP 주소 범위"

Resources:
  EKSClusterVPC:
    Type: AWS::EC2::VPC
    Properties:
      CidrBlock: !Ref VpcBlock
      EnableDnsSupport: true
      EnableDnsHostnames: true
      Tags:
        - Key: Name
          Value: !Sub ${ClusterBaseName}-VPC

  PublicSubnet1:
    Type: AWS::EC2::Subnet
    Properties:
      AvailabilityZone: !Ref AvailabilityZone1
      CidrBlock: !Ref PublicSubnet1Block
      VpcId: !Ref EKSClusterVPC
      MapPublicIpOnLaunch: true
      Tags:
        - Key: Name
          Value: !Sub ${ClusterBaseName}-PublicSubnet1

  PublicSubnet2:
    Type: AWS::EC2::Subnet
    Properties:
      AvailabilityZone: !Ref AvailabilityZone2
      CidrBlock: !Ref PublicSubnet2Block
      VpcId: !Ref EKSClusterVPC
      MapPublicIpOnLaunch: true
      Tags:
        - Key: Name
          Value: !Sub ${ClusterBaseName}-PublicSubnet2

  InternetGateway:
    Type: AWS::EC2::InternetGateway
    Properties:
      Tags:
        - Key: Name
          Value: !Sub ${ClusterBaseName}-InternetGateway

  VPCGatewayAttachment:
    Type: AWS::EC2::VPCGatewayAttachment
    Properties:
      InternetGatewayId: !Ref InternetGateway
      VpcId: !Ref EKSClusterVPC
    DependsOn: InternetGateway

  PublicRouteTable:
    Type: AWS::EC2::RouteTable
    Properties:
      VpcId: !Ref EKSClusterVPC
      Tags:
        - Key: Name
          Value: !Sub ${ClusterBaseName}-PublicRouteTable

  DefaultRoute:
    Type: AWS::EC2::Route
    Properties:
      RouteTableId: !Ref PublicRouteTable
      DestinationCidrBlock: 0.0.0.0/0
      GatewayId: !Ref InternetGateway

  PublicSubnet1RouteTableAssociation:
    Type: AWS::EC2::SubnetRouteTableAssociation
    Properties:
      SubnetId: !Ref PublicSubnet1
      RouteTableId: !Ref PublicRouteTable

  PublicSubnet2RouteTableAssociation:
    Type: AWS::EC2::SubnetRouteTableAssociation
    Properties:
      SubnetId: !Ref PublicSubnet2
      RouteTableId: !Ref PublicRouteTable

Outputs:
  VPCId:
    Description: "생성된 VPC의 ID"
    Value: !Ref EKSClusterVPC

  PublicSubnets:
    Description: "생성된 퍼블릭 서브넷들의 ID"
    Value: !Join
      - ","
      - [!Ref PublicSubnet1, !Ref PublicSubnet2]

  RouteTableId:
    Description: "생성된 퍼블릭 라우트 테이블의 ID"
    Value: !Ref PublicRouteTable
