apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig
metadata:
  name: tjv-prd-cluster
  region:  ap-northeast-2
vpc:
  subnets:
    private:
      ap-northeast-2a: { id: subnet-044b68726bcdceec2 }
      ap-northeast-2c: { id: subnet-0c09311e38fb2d5c2 }

nodeGroups:
  - name: TJV-PRD-NG-worker1
    labels: { role: workers }
    instanceType: t3.medium
    desiredCapacity: 1
    minSize: 1
    maxSize: 4
    privateNetworking: true
    subnets:
      - subnet-044b68726bcdceec2
    iam:
      withAddonPolicies:
        imageBuilder: true

  - name: TJV-PRD-NG-worker2
    labels: { role: workers }
    instanceType: t3.medium
    desiredCapacity: 1
    minSize: 1
    maxSize: 4
    privateNetworking: true
    subnets:
      - subnet-0c09311e38fb2d5c2
    iam:
      withAddonPolicies:
        imageBuilder: true
