apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: concert-tomcat
  name: concert-tomcat-svc
  namespace: back-end
spec:
  ports:
  - port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app: concert-tomcat
  type: ClusterIP
  clusterIP: 172.20.30.200
status:
  loadBalancer: {}
