apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: login-nginx
  name: login-nginx
  namespace: front-end
spec:
  replicas: $(LOGIN_NGINX_REPLICA_COUNT)
  selector:
    matchLabels:
      app: login-nginx
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
  template:
    metadata:
      labels:
        app: login-nginx
    spec:
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - weight: 100
            podAffinityTerm:
              labelSelector:
                matchLabels:
                  app: login-nginx
              topologyKey: kubernetes.io/hostname
      topologySpreadConstraints:
      - maxSkew: 1
        topologyKey: topology.kubernetes.io/zone
        whenUnsatisfiable: DoNotSchedule
        labelSelector:
          matchLabels:
            app: login-nginx
      containers:
      - name: login-nginx
        image: $(LOGIN_NGINX_IMAGE)
        ports:
        - containerPort: 80
        livenessProbe:
          httpGet:
            path: /
            port: 80
          initialDelaySeconds: 30
          periodSeconds: 10
          timeoutSeconds: 30
        readinessProbe:
          tcpSocket:
            port: 80
          initialDelaySeconds: 30
          periodSeconds: 10
          timeoutSeconds: 30
        resources:
          requests:
            memory: 100Mi
            cpu: 60m
          limits:
            memory: 100Mi
            cpu: 60m
