apiVersion: apps/v1
kind: Deployment
metadata:
  name: concert-tomcat
spec:
  replicas: 2
  template:
    spec:
      containers:
      - name: concert-tomcat
        image: 381492217459.dkr.ecr.ap-northeast-2.amazonaws.com/concert-tomcat:basic
