apiVersion: apps/v1
kind: Deployment
metadata:
  name: concert-nginx
spec:
  replicas: 2
  template:
    spec:
      containers:
      - name: concert-nginx
        image: 381492217459.dkr.ecr.ap-northeast-2.amazonaws.com/concert-nginx:v2.0
