apiVersion: apps/v1
kind: Deployment
metadata:
  name: login-nginx
spec:
  replicas: 2
  template:
    spec:
      containers:
      - name: login-nginx
        image: 381492217459.dkr.ecr.ap-northeast-2.amazonaws.com/login-nginx:v3.0
