apiVersion: apps/v1
kind: Deployment
metadata:
  name: login-tomcat
spec:
  replicas: 2
  template:
    spec:
      containers:
      - name: login-tomcat
        image: 381492217459.dkr.ecr.ap-northeast-2.amazonaws.com/login-tomcat:basic
