apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx
spec:
  replicas: 2
  template:
    spec:
      containers:
      - name: nginx
        image: 381492217459.dkr.ecr.ap-northeast-2.amazonaws.com/root-nginx:v3.0
