apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: concert-nginx-hpa
  namespace: front-end
spec:
  maxReplicas: 10
  minReplicas: 2
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: concert-nginx
  targetCPUUtilizationPercentage: 20
