apiVersion: v1
kind: Service
metadata:
  labels:
    app: concert-nginx
  name: concert-nginx-svc
  namespace: front-end
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: concert-nginx
  type: LoadBalancer
